import type { Metadata } from 'next'

import { TransactionProvider } from '@/store/transactions-context'
import './globals.css'

export const metadata: Metadata = {
	title: 'My Finance',
	description: 'Generated by create Lukas Coding',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='en'>
			<body>
				<TransactionProvider>
					{children}
					<div id='modal-root'></div>
				</TransactionProvider>
			</body>
		</html>
	)
}
